DushinWebApp/Models/Package.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DushinWebApp.Models
{
    public class Package
    {
        public int PackageId { get; set; }
        public string Name { get; set; }
        public string LocName { get; set; }
        public string LocState { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int LocationId { get; set; }
        public string Picture { get; set; }
        public bool Active { get; set; }
        public string UserId { get; set; }
    }
}

DushinWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DushinWebApp.Models;
using DushinWebApp.Services;
using DushinWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace DushinWebApp.Controllers
{
    public class OrderController : Controller
    {
        private IDataService<Order> _orderService;
        private IDataService<Package> _packageService;
        private UserManager<IdentityUser> _userManagerService;
        public OrderController(IDataService<Order> orderService,IDataService<Package> packageService,
                                UserManager<IdentityUser> managerService)
        {
            _orderService = orderService;
            _packageService = packageService;
            _userManagerService = managerService;
        }
        [HttpGet]
        public IActionResult Purchase(string name)
        {
            Package pac = _packageService.GetSingle(p => p.Name == name);
            OrderPurchaseViewModel vm = new OrderPurchaseViewModel
            {
                Name = pac.Name,
                Description=pac.Description,
                Price = pac.Price
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Purchase(OrderPurchaseViewModel vm)
        {
            Package pac = _packageService.GetSingle(p => p.Name == vm.Name);
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);
            Order ord = new Order
            {
                UserId = user.Id,
                Price = vm.Price,
                Name = vm.Name,
                Date = DateTime.Now
            };
            _orderService.Create(ord);
            return RedirectToAction("Details", "Package", new { name = vm.Name });
        }
    }
}

DushinWebApp/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DushinWebApp.Models;
using DushinWebApp.Services;
using DushinWebApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Diagnostics;

namespace DushinWebApp.Controllers
{
    public class PackageController : Controller
    {
        private UserManager<IdentityUser> _userManagerService;
        private IDataService<Location> _locationService;
        private IDataService<Package> _packageService;
        private IDataService<Feedback> _feedbackService;
        private IHostingEnvironment _environment;
        public PackageController(UserManager<IdentityUser> managerService, IDataService<Location> locationService,
            IDataService<Package> packageService, IHostingEnvironment environment, IDataService<Feedback> feedbackService)
        {
            _locationService = locationService;
            _packageService = packageService;
            _environment = environment;
            _userManagerService = managerService;
            _feedbackService = feedbackService;
        }
        public IActionResult AllPackages()
        {
            IEnumerable<Package> list = _packageService.GetAll().Where(p=>p.Active==true);

            PackageHomeViewModel vm = new PackageHomeViewModel
            {
                PackagesCarousel = new Package[3],
                PackageNSW = new Package[3],
                PackageInt = new Package[3]
            };
            int i = 0;
            foreach (var item in list)
            {
                if (i == 3) break;
                if (item.Active)
                {
                    vm.PackagesCarousel[i] = item;
                    i++;
                }
            }
            i = 0;
            foreach (var item in list)
            {
                if (i == 3) break;
                if (item.Active && item.LocState.ToUpper() == "NSW")
                {
                    vm.PackageNSW[i] = item;
                    i++;
                }
            }
            i = 0;
            foreach (var item in list)
            {
                if (i == 3) break;
                if (item.Active && item.LocState.ToUpper() != "NSW")
                {
                    vm.PackageInt[i] = item;
                    i++;
                }
            }
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string name)
        {
            Package pac = _packageService.GetSingle(p => p.Name == name);
            List<Feedback> list = _feedbackService.Query(f => f.PackageId == pac.PackageId).OrderBy(f=>f.ComntDate).ToList();
            IdentityUser user = await _userManagerService.FindByIdAsync(pac.UserId);
            PackageDetailsViewModel vm = new PackageDetailsViewModel
            {
                Name = pac.Name,
                LocationName = _locationService.GetSingle(l=>l.LocationId==pac.LocationId).Name,
                Price = pac.Price,
                Description = pac.Description,
                Picture = pac.Picture,
                UserName = user.UserName,
                Feedbacks=list
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Details(PackageDetailsViewModel vm)
        {
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);
            Package package = _packageService.GetSingle(p => p.Name == vm.Name);
            Feedback feedback = new Feedback
            {
                UserId = user.Id,
                PackageId = package.PackageId,
                ComntDate = DateTime.Now,
                Comment = vm.NewFeedback,
                UserName = User.Identity.Name
            };
            _feedbackService.Create(feedback);
            return RedirectToAction("Details", "Package",new {name=vm.Name });
        }
        [HttpGet]
        [Authorize(Roles = "Provider")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> Create(PackageCreateViewModel vm, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);
                //check exists - Name = UNQ
                Package existingPackage = _packageService.GetSingle(p => p.Name == vm.Name);
                Location loc = _locationService.GetSingle(l => l.LocationId == int.Parse(TempData["locId"].ToString()));
                if (existingPackage == null)
                {
                    Package pac = new Package
                    {
                        LocationId = loc.LocationId,
                        Name = vm.Name,
                        LocName = loc.Name,
                        Price=vm.Price,
                        Description = vm.Description,
                        Active=vm.Active,
                        LocState = loc.State,
                        UserId = user.Id

                    };
                    //upload the picture to the file system
                    //assign the picture URL to the cat object
                    if (file != null)
                    {
                        //check ??

                        //upload server path
                        var serverPath = Path.Combine(_environment.WebRootPath, "uploads");
                        //create a folder
                        Directory.CreateDirectory(Path.Combine(serverPath, User.Identity.Name));
                        //get the file name
                        string fileName = FileNameHelper.GetNameFormated(Path.GetFileName(file.FileName));

                        //stream the file to the server
                        using (var fileStream = new FileStream(Path.Combine(serverPath, User.Identity.Name, fileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                        }
                        //assign the picture URL to the cat object
                        pac.Picture = User.Identity.Name + "/" + fileName;
                    }

                    //save to db
                    _packageService.Create(pac);
                    //go home
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.MyMessage = "Package name exists. Please change the name";
                    return View(vm);
                }
            }
            else
            {
                return View(vm);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> Update(string name)
        {
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);

            Package pac = _packageService.GetSingle(p => p.Name == name);
            if (pac.UserId == user.Id) {
            PackageUpdateViewModel vm = new PackageUpdateViewModel
            {
                PackageId=pac.PackageId,
                Name = pac.Name,
                LocName = pac.LocName,
                Description = pac.Description,
                Price = pac.Price,
                Picture = pac.Picture,
                LocState = pac.LocState,
                Active = pac.Active
            };
                return View(vm);
            }
            else
            {
                return RedirectToAction("DeniedPackage", "Account");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> Update(PackageUpdateViewModel vm, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                Package package = _packageService.GetSingle(p=>p.PackageId==vm.PackageId);
                package.Name = vm.Name;
                package.LocName = vm.LocName;
                package.Price = vm.Price;
                package.Description = vm.Description;
                package.LocState = vm.LocState;
                package.Active = vm.Active;
                    //Package pac = new Package
                    //{
                    //    LocationId = int.Parse(TempData["locId"].ToString()),
                    //    Name = vm.Name,
                    //    Price = vm.Price,
                    //    Description = vm.Description,
                    //    Active = vm.Active,
                    //    Picture=vm.Picture
                    //};
                    //upload the picture to the file system
                    //assign the picture URL to the cat object
                if (file != null)
                    {
                        //check ??

                        //upload server path
                        var serverPath = Path.Combine(_environment.WebRootPath, "uploads");
                        //create a folder
                        Directory.CreateDirectory(Path.Combine(serverPath, User.Identity.Name));
                        //get the file name
                        string fileName = FileNameHelper.GetNameFormated(Path.GetFileName(file.FileName));

                        //stream the file to the srever
                        using (var fileStream = new FileStream(Path.Combine(serverPath, User.Identity.Name, fileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                        }
                        //assign the picture URL to the cat object
                        package.Picture = User.Identity.Name + "/" + fileName;
                        //string oldPicturePath = "~/uploads/" +  vm.Picture;

DushinWebApp/Views/Package/AllPackages.cshtml
@model PackageHomeViewModel
<section>
    <div class="container">
        <div id="carouselExampleControls" class="carousel slide bg-dark" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item card m-0 active">
                    <div class="row">
                        @if (Model.PackagesCarousel[0] != null)
                        {
                            
                        <div class="col-md-4 p-3">
                            <div class="row justify-content-center">
                                <div class="col-10">
                                    <h5 class="card-title" style="font-size:1.5em">@Model.PackagesCarousel[0].Name</h5>
                                    <p class="text-body" style="font-size:1.5em">@Model.PackagesCarousel[0].Description</p>
                                    <h5 class="card-title" style="font-size:1.5em">$@Model.PackagesCarousel[0].Price</h5>
                                    <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[0].Name" class="btn btn-primary">More</a>
                                </div>
                            </div>
                        </div>
                                <div class="col-md-8">
                                    <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[0].Name">
                                        <img class="img-fluid" src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.PackagesCarousel[0].Picture" style="max-width:750px;max-height:450px" alt="slide 1">
                                        </a>
                                </div>
                                }
                                else
                                {
                                <div class="col-md-4 p-3">
                                    <div class="row justify-content-center">
                                        <div class="col-10">
                                            <h5 class="card-title" style="font-size:1.5em">Title</h5>
                                            <p class="text-body" style="font-size:1.5em">Description</p>
                                            <h5 class="card-title" style="font-size:1.5em">$0</h5>
                                            </div>
                                        </div>
                                        </div>
                                        <div class="col-md-8">
                                            <img src="http://placehold.it/784x484" class="img-fluid w-100" alt="slide 1">
                                        </div>

                                        }
                                    </div>
                                </div>
                <div class="carousel-item card m-0">
                    <div class="row">
                        @if (Model.PackagesCarousel[1] != null)
                        {

                            <div class="col-md-4 p-3">
                                <div class="row justify-content-center">
                                    <div class="col-10">
                                        <h5 class="card-title" style="font-size:1.5em">@Model.PackagesCarousel[1].Name</h5>
                                        <p class="text-body" style="font-size:1.5em">@Model.PackagesCarousel[0].Description</p>
                                        <h5 class="card-title" style="font-size:1.5em">$@Model.PackagesCarousel[1].Price</h5>
                                        <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[1].Name" class="btn btn-primary">More</a>
                                    </div>
                                    </div>
                                </div>
                                    <div class="col-md-8">
                                        <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[1].Name">
                                            <img src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.PackagesCarousel[1].Picture" style="max-width:750px;max-height:450px" alt="slide 2">
                                        </a>
                                    </div>
                                    }
                                    else
                                    {
                                    <div class="col-md-4 p-3">
                                        <div class="row justify-content-center">
                                            <div class="col-10">
                                                <h5 class="card-title" style="font-size:1.5em">Title</h5>
                                                <p class="text-body" style="font-size:1.5em">Description</p>
                                                <h5 class="card-title" style="font-size:1.5em">$0</h5>
                                            </div>
                                            </div>
                                        </div>
                                            <div class="col-md-8">
                                                <img src="http://placehold.it/784x484" class="img-fluid w-100" alt="slide 2">
                                            </div>

                                            }
                                        </div>
                                    </div>
                <div class="carousel-item card m-0">
                    <div class="row">
                        @if (Model.PackagesCarousel[2] != null)
                        {

                        <div class="col-md-4 p-3">
                            <div class="row justify-content-center">
                                <div class="col-10">
                                    <h5 class="card-title" style="font-size:1.5em">@Model.PackagesCarousel[2].Name</h5>
                                    <p class="text-body" style="font-size:1.5em">@Model.PackagesCarousel[2].Description</p>
                                    <h5 class="card-title" style="font-size:1.5em">$@Model.PackagesCarousel[2].Price</h5>
                                    <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[2].Name" class="btn btn-primary">More</a>
                                </div>
                                </div>
                            </div>
                                <div class="col-md-8">
                                    <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackagesCarousel[2].Name">
                                        <img src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.PackagesCarousel[2].Picture" style="max-width:750px;max-height:450px" alt="slide 3">
                                    </a>
                                </div>
                                }
                                else
                                {
                                <div class="col-md-4 p-3">
                                    <div class="row justify-content-center">
                                        <div class="col-10">
                                            <h5 class="card-title" style="font-size:1.5em">Title</h5>
                                            <p class="text-body" style="font-size:1.5em">Description</p>
                                            <h5 class="card-title" style="font-size:1.5em">$0</h5>
                                        </div>
                                        </div>
                                    </div>
                                        <div class="col-md-8">
                                            <img src="http://placehold.it/784x484" class="img-fluid w-100" alt="slide 3">
                                        </div>

                                        }
                                    </div>
                                </div>
                </div>
            <a class="carousel-control-prev" style="max-width:50px" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" style="max-width:50px" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    </section>
<section class="border-top-0">
    <div class="container">
        <div class="row text-center justify-content-center">
            <div class="col col-12 col-md-9 col-lg-8">
                <h2 class="display-4">NSW packages</h2>
                <p class="lead">Find the best NSW packages with Grande Travel. Search a fantastic range of packages and book your best escape.</p>
            </div>
        </div>
        <div class="row text-center justify-content-center">
            @for(int i = 0; i < Model.PackageNSW.Length; i++) {
            <div class="card border-0 col-md-3 bg-light">
                @if (Model.PackageNSW[i] != null)
    {
            <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackageNSW[i].Name" class="card">
                <img class="d-block w-100 p-0" src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.PackageNSW[i].Picture">
                <div class="card-body">
                    <p class="card-title">@Model.PackageNSW[i].Name</p>
                    <p class="card-text">$@Model.PackageNSW[i].Price</p>
                </div>
            </a>
}
else
{
            <img class="d-block img-fluid p-0" src="http://placehold.it/350x180?text=2">

            <div class="card-body">
                <p class="card-title">Title</p>
                <p class="card-text">$0</p>
            </div>}
            </div>
                }
            
            @*<div class="card border-0 col-md-3">
                <a class="card" href="#">
                    <img class="d-block w-100" src="//placehold.it/286x180?text=4" alt="slide 1">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                    </div>
                </a>
            </div>
            <div class="card border-0 col-md-3">
                <a class="card" href="#">
                    <img class="d-block w-100" src="//placehold.it/286x180?text=4" alt="slide 1">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                    </div>
                </a>
            </div>*@
        </div>
        <div class="row text-center justify-content-center">
            <div class="col col-12 col-md-9 col-lg-8">
                <h2 class="display-4">Interstate packages</h2>
                <p class="lead">Find the best interstate packages across Australia with Grande Travel. Search a fantastic range of interstate packages in NT, QLD, WA and more. Don't hesitate, book today.</p>
            </div>
        </div>
        <div class="row text-center justify-content-center">
            @for (int i = 0; i < Model.PackageInt.Length; i++)
    {<div class="card border-0 col-md-3 bg-light">
    @if (Model.PackageInt[i] != null)
    {
        <a asp-action="Details" asp-controller="Package" asp-route-name="@Model.PackageInt[i].Name" class="card">
            <img class="d-block w-100 p-0" src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.PackageInt[i].Picture">
            <div class="card-body">
                <p class="card-title">@Model.PackageInt[i].Name</p>
                <p class="card-text">$@Model.PackageInt[i].Price</p>
            </div>
        </a>
    }
    else
    {
        <img class="d-block img-fluid p-0" src="http://placehold.it/350x180?text=2">

        <div class="card-body">
            <p class="card-title">Title</p>
            <p class="card-text">$0</p>
        </div>}
</div>
}
            @*<div class="card border-0 col-md-3">
            <a class="card" href="#">
                <img class="d-block w-100" src="//placehold.it/286x180?text=4" alt="slide 1">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                </div>
            </a>
        </div>
        <div class="card border-0 col-md-3">
            <a class="card" href="#">
                <img class="d-block w-100" src="//placehold.it/286x180?text=4" alt="slide 1">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                </div>
            </a>
        </div>*@
        </div>
    </div>
</section>

DushinWebApp/Views/Package/Details.cshtml
@model PackageDetailsViewModel

<section class="bg-white fullwidth-split">
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-12 col-sm-5 col-lg-6 order-sm-2 fullwidth-split-image d-sm-flex align-items-center">
                <img alt="Image" src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@Model.Picture" class="bg-image">
            </div>
            <!--end of col-->
            <div class="col-12 col-sm-7 col-lg-6 order-sm-1 fullwidth-split-text">
                <div class="col-12 col-sm-8">
                    <h3 class="display-4">@Model.Name</h3>
                    <span class="lead">
                        Location: @Model.LocationName
                    </span>
                    <span class="lead">
                        @Model.Description
                    </span>
                    <h4 class="display-4">$@Model.Price</h4>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
                    {
                <a asp-action="Purchase" asp-controller="Order" asp-route-name="@Model.Name" class="btn btn-outline-primary btn-lg">Buy</a>

}
else
{
                <a asp-action="Login" asp-controller="Account" class="btn btn-outline-primary btn-lg">Buy</a>

}
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Provider") && Model.UserName==User.Identity.Name)
    {
                <a asp-action="Update" asp-controller="Package" asp-route-name="@Model.Name" class="btn btn-outline-primary btn-lg">Update</a>
}
                </div>
            </div>
            <!--end of col-->
        </div>
        <a asp-action="Details" asp-controller="Location" asp-route-name="@Model.LocationName">Back to location</a>
    </div>
</section>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <p class="lead">Comments:</p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model.Feedbacks)
        {
            <div class="col-12 border-bottom">
                <span><b>@item.UserName </b></span><p>@item.ComntDate</p>
                <p>@item.Comment</p>
            </div>
    }
        </div>

        @if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
    {
        <div class="row">
            <div class="col">
                <p class="lead">
                    Leave your comment:
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <form asp-action="Details" asp-controller="Package" method="post" class="form-inline">
                    <input asp-for="@Model.NewFeedback" class="form-control mr-sm-2" type="text" />
                    <input asp-for="@Model.Name" type="hidden" readonly />
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Post</button>
                </form>
            </div>
        </div>}
    </div>
</section>

DushinWebApp/Views/Package/ProviderPackages.cshtml
@model AccountProviderPackagesViewModel

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col card-body">
                <h1 class="display-4 text-indigo">@User.Identity.Name packages</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-3 col-lg-4">
                <p class="lead">Packages available: @Model.Total</p>
            </div>
            @*<div class="col-12 col-md-3 col-lg-2">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Filter
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" asp-action="Details" asp-controller="Location" asp-route-name="@Model.Name" asp-route-sorting="hight">Highest price</a>
                        <a class="dropdown-item" asp-action="Details" asp-controller="Location" asp-route-name="@Model.Name" asp-route-sorting="low">Lowest price</a>
                    </div>
                </div>
            </div>*@
        </div>
        <div class="row">

            @foreach (var item in Model.Packages)
            {<div class="col-md-3">
                    <div class="card">
                        <a asp-action="Details" asp-controller="Package" asp-route-name="@item.Name">
                            <img class="d-block w-100" src="https://dushintravelappstorage.blob.core.windows.net/travelappcontainer/uploads/@item.Picture" alt="slide 1">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">$@item.Price</p>
                            <a asp-action="Details" asp-controller="Package" asp-route-name="@item.Name" class="btn btn-primary">More</a>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>